let a = 100;
let b = 25;
console.log("a=" + a, "b=" + b, "a+b=", a + b);
console.log("a=" + a, "b=" + b, "a-b=", a - b);
console.log("a=" + a, "b=" + b, "a*b=", a * b);
console.log("a=" + a, "b=" + b, "a/b=", a / b);
console.log("a=" + a, "b=" + b, "a%b=", a % b);
console.log("a=" + a, "b=" + b, "a**b=", a ** b);
console.log("Assigment operators");
a = 25;
console.log("a=" + a, "a+=10", (a += 10));
console.log("a=" + a, "a-=10", (a -= 10));
console.log("a=" + a, "a/=10", (a /= 10));
a = 25;
console.log("a=" + a, "a*=10", (a *= 10));
a = 25;
console.log("a=" + a, "a/=10", (a /= 10));
a = 25;
console.log("a=" + a, "a%=10", (a %= 10));
console.log("Caomparator opertaors");
a = 100;
b = 25;
console.log("a<b", "a=" + a, "b=" + b, a < b);
console.log("a>b", "a=" + a, "b=" + b, a > b);
console.log("a<=b", "a=" + a, "b=" + b, a <= b);
console.log("a>=b", "a=" + a, "b=" + b, a >= b);
console.log("logical operators");
console.log("a = 100,b = 25");
console.log("a > b && b < a", a > b && b < a);
console.log("a < b && b < a", a < b && b < a);
console.log("a < b || b < a", a < b || b < a);
console.log("!(a < b)", !(a < b));
